### ISSUE TITLE
PrefixInForStatementRemover

### ISSUE THREAD

**Issue by riiji** [TEF-Y/Main#10]
### Ревью https://github.com/riiji/PrefixIncrementorForRemover

Таска: Заменить все преинкременторы/предекременторы в цикле for 

Короч есть такие траблы что прога работает с некоторыми **минорными** багами

Проблема заключается в том, что когда в цикле находятся 2 инкрементора, то при попытке исправления **второго** инкрементора, прога фиксит **первый** инкрементор

Вторая проблема заключается в том что при наводке на проблемный код, анализатор пишет что в нем содержится lowercase letter (это автокод при создании), но при этом в проекте я не нашел ничего про lowercase letter, после этой надписи он пишет что итератор префиксный

**Comment by riiji** [comment]
По поводу первой проблемы у меня есть идеи решения, выглядит они вот так

1. Получать не ноду с циклом for, а любой преинкремент/предекремент чекать у него родителя и если его родителем будет `ForStatementSyntax` и эта нода будет находится в `ForStatementSyntax.Incrementors`, то ее нужно заменить. 
Звучит ультракринжово, но в целом это фиксит данную проблему

2. Фиксить все инкременторы одновременно

**Comment by InRedikaWB** [comment]
Обсудили ирл, но для протокола.
Сейчас особо ревьювить нечего, потому что это похоже на прототип на коленке. Он работает только с инкрементами в for'е. Если есть планы с этим дальше работать - куда лучше думать о расширении в сторону всех инкрементов, а не обработки редкого кейса с двумя инкрементами в for'е.
