### ISSUE TITLE
Review : Calculator

### ISSUE THREAD

**Issue by hrrrrustic** [TEF-Y/Main#3]
1. Кажется это можно сделать в одну строчку https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L11

2. String.Empty? https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L14

3. Зачем else, если все равно стоят continue, вложенность фи https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L30

4. Честно говоря, не особо понимаю, что здесь вообще происходит, он же в итоге получит считанную раннее строку? https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L32

5. Почти во всех ифах стоит .Push и потом continue, наверно можно избавиться от этого копирования https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L44

6. Наверно надо кидать эксепшн, если какой-то рандом символ прилетит https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L103

7. Так и не понял, что это такое, видимо нейминг https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L13

8. Кажется это просто сплит по пробелу, что за массив там вообще
https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L125

9.1 Опять же, а если .Count < 2? Видимо над эксепшн + кажется можно проверить один раз это и не пихать везде https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L131

9.2 Как минимум везде есть два .Pop, которые можно сделать до ифов https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L131

9.3 А еще можно сделать как у меня в польской нотации, через словарик операции, и тогда гора ифов уйдет

10. Мелочь, но можно и паблики накинуть на класс и мейн

11. Какая-то очень сложная логика, завязанная на строках, очень сложно понять, что происходит. Ну и если уж оставлять так, то кажется есть смысл сделать хотя бы стрингбилдер

12. Ну опять же можно в одну строчку https://github.com/nazzrrg/Calculator/blob/master/Calculator/Program.cs#L184

**Comment by InRedikaWB** [comment]
+ Стоит подумать на счет выделения логикик в отдельные методы. Это проще читать чем 200 строк спошного кода.

+ Этот кусок написан несколько раз с разницей в один символ.
https://github.com/nazzrrg/Calculator/blob/82847cecc7bcd6c591035d0952ea0b1fa1b413d2/Calculator/Program.cs#L139-L147

**Comment by InRedikaWB** [comment]
Outdate.
