### ISSUE TITLE
Review: VkQueue

### ISSUE THREAD

**Issue by riiji** [TEF-Y/Main#4]
ебашь
https://github.com/riiji/VkQueue

**Comment by InRedikaWB** [comment]
@riiji 

1. **Readme**. В описании команд бы добавить еще аргументы команд
2. [**VkQueue**](https://github.com/riiji/VkQueue/blob/master/VkQueue/VkQueue.cs). Делать класс со статик полями - идея не очень хорошая с точки зрения ООП. Лучше класс и статический его экземпляр. (Тогда не нужно будет Utilities.ClearQueue)
```C#
public class CommonTypeAccessor
{
    public static CommonTypeAccessor Instance = new CommonTypeAccessor();

    public readonly Column<CommonTypeAccessor, Int32> Id;
    public readonly Column<CommonTypeAccessor, String> Name;
    public readonly Column<CommonTypeAccessor, Guid> RowGuid;
    public readonly Column<CommonTypeAccessor, DateTime> ModifiedDate;
}
```
3. [**VkQueue.Contains**](https://github.com/riiji/VkQueue/blob/master/VkQueue/VkQueue.cs). Можно было просто через ConversationQueue.Any(u => u.Id == obj.Id) реализовать проверку эту.
4. [**VkResponse**](https://github.com/riiji/VkQueue/blob/master/VkQueue/VkObjects/VkResponse.cs). Ts - не знаю что это, но оно даже не юзается.
5. [**VkResponse**](https://github.com/riiji/VkQueue/blob/master/VkQueue/VkObjects/VkResponse.cs). dynamic - максимально не стоит юзать динамик. Абсолютно не понятно, что это и как с этим работать. В апи же описан объект, который возвращается, почему бы не описать его и не получить его нормально через десериализацию?
6. **VkModule**. А теперь почувствуй себя гуру ООП и сделай методы этого класса не статик. Как минимум, VkModule - это класс, который всегда хранит VkApi. Почему бы не засунуть его внутрь, зачем его каждый раз получать как аргумент?
7. [**RequestHelper**](https://github.com/riiji/VkQueue/blob/master/VkQueue/RequestHelper.cs). RequestHandlerAsync - я надеюсь, что это уйдет в рамках фикса 5.
8. [**RequestHelper**](https://github.com/riiji/VkQueue/blob/master/VkQueue/RequestHelper.cs). CommandHandler - `text.Substring(0, spaceIndex);` - метод String.Trim
9. [**RequestHelper**](https://github.com/riiji/VkQueue/blob/master/VkQueue/RequestHelper.cs). CommandHandler - `case "push" when conversationId < 2000000000`
10. [**RequestHelper**](https://github.com/riiji/VkQueue/blob/master/VkQueue/RequestHelper.cs). CommandHandler - Я бы еще добавил `default ` и хотя бы логировал, что команды такой нет. Ну или же отвечать, но тут уже хз будет ли это спамом.

**Comment by riiji** [comment]
1. Я бы добавил, если бы они были :)
2. Понял, исправлю
3. Да, похоже на правду
4. По документации ВК, используется на https://github.com/riiji/VkQueue/blob/master/VkQueue/Program.cs#L27
5. Каким образом? в апи написано что updates состоит из хз скольки элементов и содержит хз что, поэтому и используется dynamic, да, согласен с тем что dynamic это не очень хорошо, хотя тут он вписывается вполне неплохо
6. Да, я понял о чем ты пишешь, исправлю
7. Не понял как фиксить 5
8. Да
9. Да, push можно делать в личку бота тоже, чтобы не спамить, но эта хрень касается и других команд, так что я это использую
10. Можно засунуть `default: break;` учитывая сколько сообщений приходит в беседе я бы не логировал, отвечать точно не надо, мы же так ахуеем, а в итоге вк попросит ввести капчу и бот чуть чуть сломается

**Comment by InRedikaWB** [comment]
https://github.com/riiji/VkQueue/blob/master/VkQueue/VkObjects/VkModule.cs#L140-L148

Выглядит как очень плохой способ лловить ошибки. Если ты пишешь кетч, то ты должен либо обработать ситуацию, либо пробросить ошибку. Сейчас ты логируешь и просто возвращаешь null, хотя выполнять код дальше уже нельзя т.к. юзера нет. Понятно, что ты сразу же подпер костылем ввиде `if (user == null) return`, но это так себе способ) Эксепшены на то и нужны, чтобы ты мог прервать выполнение нормально. Я бы советовал попробовать переписать, в таких кетчах пробрасывать свое исключение (VkBotException) куда запихаешь тот текст, что логируешь, а где-то в одном месте, где у тебя хендлятся все команты - написать уже кетч, который будет логировать (потому что дальше пробрасывать ты не можешь).

https://github.com/riiji/VkQueue/blob/master/VkQueue/VkObjects/VkModule.cs

Сейчас будет больно, нужно будет думать. Будь готов, что ты не раз перепишешь код, но в итоге поймешь, что результат того стоит. Ты сильно обмазался статиками, а это довольно плохо т.к. сильно усложняет понимание, делает код почти не тестируемым. Я предлагаю начать с этого класс. Попробуй его реализовать с минимальным кол-вом вызовов к статикам. Нужно откуда-то прочитать - принимай как аргумент. Нужно какую-то инфу получить - возвращай из метода.

**Comment by riiji** [comment]
https://github.com/riiji/VkQueue вроде что то сделал, го дальше
