### ISSUE TITLE
не все роли

### ISSUE THREAD

**Issue by riiji** [TEF-Y/Main#5]
https://github.com/TEF-Y/Main/blob/master/Discord%20roles.md
нет роли сектанта, то ли первак изменился на сектанта, то ли это новая роль

**Comment by InRedikaWB** [comment]
Да, ренеймил т.к. мы немного забросили эту тему с ролями. Фантазии не сильно то хватило, а чтобы нормально определять требования, нужно обкатать их сначала :3
